### ISSUE TITLE
Make Download Report a PDF and Visually Appealing

### ISSUE THREAD

**Issue by marshalmiller** [rottingresearch/rottingresearch#108]
Right now, the download report saves an HTML version of the page with unformatted text and looks pretty bad. It would be great to be able to have this report look as good as the site does.

**Comment by Deepanshusaxena1** [comment]
Hi @marshalmiller, I want to work on this issue.
Can you please assign this issue to me?

**Comment by marshalmiller** [comment]
@Deepanshusaxena1 thank you for your willingness to help. It's yours.

**Comment by aditirao7** [comment]
Hey @marshalmiller I'll work on this
