### ISSUE TITLE
Number of arxiv and DOI references not updating

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#144]
**Describe the bug**
The number of arxiv and DOI issue do not seem to reflect on the top of the report.

**To Reproduce**
1. Go to [rottingresearch.org](https://rottingresearch.org)
2. Upload [2206.00785.pdf](https://arxiv.org/pdf/2206.00785.pdf)
3. Number of arxiv and DOI references shows 0

**Expected behavior**
Should show 3 and 2 respectively.

**Screenshots**
![image](https://github.com/rottingresearch/rottingresearch/assets/57457307/93027c88-058e-438c-9f77-2ea6ff5c07bc)
![image](https://github.com/rottingresearch/rottingresearch/assets/57457307/87793601-69cd-4e87-a063-34375363c7e9)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Browser: Chrome
 - Version: 117.0.5938.92

**Comment by marshalmiller** [comment]
Fixed in #146
