### ISSUE TITLE
Few links have incorrect status 

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#145]
**Describe the bug**
A few of the links show status N/A although their redirect URLs lead to 200 status pages.

**To Reproduce**
1. Go to [rottingresearch.org](https://rottingresearch.org/)
2. Upload [2206.00785.pdf](https://arxiv.org/pdf/2206.00785.pdf)
3. Number of arxiv and DOI references shows 0

**Expected behavior**
Should show 200 status for the last 2 arxiv links.

**Screenshots**
![image](https://github.com/rottingresearch/rottingresearch/assets/57457307/f41fd788-3a16-48b2-877b-48368765ad40)

Desktop (please complete the following information):
- OS: Linux (Ubuntu 20.04)
- Browser: Chrome
- Version: 117.0.5938.92

**Comment by gpuligundla** [comment]
Hi @marshalmiller, can i work on this

**Comment by marshalmiller** [comment]
@gpuligundla It's all yours. Thank you for your help.

**Comment by marshalmiller** [comment]
@gpuligundla There is a decent chance that the issue stems from the Python library for this project. Here is a link. Feel free to fix it there, if that's the issue, and I will bring it to this project ASAP.

https://github.com/rottingresearch/linkrot

**Comment by gpuligundla** [comment]
sure, I'm currently triaging the issue. please allow me some more time

**Comment by marshalmiller** [comment]
@gpuligundla Oh. No rush at all. I just wanted to make sure you were aware that the Linkrot library was intrinsically tied to our project, and it might be valuable to look there if you get stuff. Take your time. We appreciate any help or guidance you can provide.

**Comment by marshalmiller** [comment]
This was addressed in PR #198 . Thank you @gpuligundla for your great work and a well-detailed PR.
