### ISSUE TITLE
Update CSS to add a few pixels of space between buttons

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#148]
On the analysis page, the 2 download buttons have no space between them which can be noticed on hovering over them. I think adding some space in between would make the page look much better. This could be a good first issue to pick up.

**Comment by Arnav7107** [comment]
Hey @aditirao7 I would love to contribute to this isssue. Can you please assign this task to me?

**Comment by aditirao7** [comment]
@Arnav7107 sure, go ahead and send in a pull request. Should be a quick fix

**Comment by marshalmiller** [comment]
This was completed by @timcrob in #183
