### ISSUE TITLE
Analysis page div arrangement

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#150]
Is there a reason we are keeping the URL/PDF and DOI/arxiv sections side by side on desktop view? I think vertically stacking the sections would look more appealing, especially when one of the lists is longer than the other (the shorter list has a ton of white space under it). Attaching screenshot for clarity.

![image](https://github.com/rottingresearch/rottingresearch/assets/57457307/4a581aea-cd32-40af-88ac-e339b49f07b3)

**Comment by marshalmiller** [comment]
@aditirao7 I don't think so. I think this is a good idea.

**Comment by marshalmiller** [comment]
This was addressed by @timcrob in #183
