### ISSUE TITLE
Fix CSS for pdf report

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#152]
Currently the links in the PDF report are being cut off by page breaks, I believe this can be fixed using the property `page-break-inside: avoid` property of CSS, I attempted this but it didn't seem to work. Maybe someone with more frontend experience can help.

Here is how the pdf currently looks:
[report.pdf](https://github.com/rottingresearch/rottingresearch/files/12763171/report.pdf)

Related PR: #151

**Comment by marshalmiller** [comment]
I think we need to remove the hyperlink for downloading the PDF. Since the link won't be valid after the session has ended.

**Comment by aditirao7** [comment]
> I think we need to remove the hyperlink for downloading the PDF. Since the link won't be valid after the session has ended.

I think this can be a separate issue?

**Comment by marshalmiller** [comment]
It was addressed in a recent commit.
