### ISSUE TITLE
Add setup instructions for contributors

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#17]
Maybe contributing guidelines can be added with setup instructions on how to run the website on localhost for those not familiar with flask.

**Comment by anmolag10** [comment]
I am not able to install the package on the local system due to a conflict between the version of dependencies. Any idea how to resolve the same?
![image](https://user-images.githubusercontent.com/57227202/136320145-8738bdd7-9403-49a4-9a26-26b030b9b973.png)

**Comment by anmolag10** [comment]
pulling the updated repo with the updated version of requests package resolved the issue.

**Comment by anmolag10** [comment]
> I am not able to install the package on the local system due to a conflict between the version of dependencies. Any idea how to resolve the same? ![image](https://user-images.githubusercontent.com/57227202/136320145-8738bdd7-9403-49a4-9a26-26b030b9b973.png)

pulling the updated repo with the updated version of requests package resolved the issue.
