### ISSUE TITLE
(Update) CodeQL Github action to run only when change in Python

### ISSUE THREAD

**Issue by M-Faheem-Khan** [rottingresearch/rottingresearch#52]
I think we should update the `CodeQL/Analyze (python)` to run only when there has been changes made to python code.  As now whenever changes to any none .py code is made the CodeQL for python is still run.

![image](https://user-images.githubusercontent.com/17150767/170977494-7e4ffcc9-1243-497e-8d8b-880ed93d2b37.png)

We can also remove the `Autobuild` section from the action as there is no code compilation being done.
https://github.com/marshalmiller/rottingresearch/blob/cf3181de677964a656c41debaf366599f2a7c137/.github/workflows/codeql-analysis.yml#L56-L57

**Comment by marshalmiller** [comment]
We have streamlined GitHub Actions. This will be continually improved.
