### ISSUE TITLE
Add Link Archiving

### ISSUE THREAD

**Issue by marshalmiller** [rottingresearch/rottingresearch#72]
I'd like to add a feature that takes all links that are verified to be active and add them to the Internet Archive Wayback Machine to preserve them in time. Ideally, this would be added to the parent project, [Linkrot](https://github.com/marshalmiller/linkrot). 

The basic concept is that if you navigate to [https://web.archive.org/save/{url}](https://web.archive.org/save/%7Burl%7D) the service automatically archives that page. So after verifying that it returns a valid code, we would just connect to all of those sites, and it would create a snapshot. I'd love for this to be an option on the results page. So after all the links are checked, you have the option to archive the valid ones only. This way it is optional, and we don't take more resources than we need. 

Another option would be to use [ArchiveNow](https://github.com/oduwsdl/archivenow). This repository isn't updated regularly, so I'd prefer using Linkrot, but if this is the easiest way to achieve the desired outcome, I am OK with that.

Anyone able to complete this task, please take a stab at it.

**Comment by marshalmiller** [comment]
@mailtodanish was kind enough to add this functionality to Linkrot at the link below. I'd prefer we used this to add this option to the results page of this project.

https://github.com/marshalmiller/linkrot/blob/main/linkrot/archive.py

**Comment by mailtodanish** [comment]
@marshalmiller I think we need to implement Radis for this. multiple request response errors. I am exploring the proper way to implement Radis.

**Comment by marshalmiller** [comment]
@mailtodanish thank you.
