### ISSUE TITLE
Remove Paste a Link Feature

### ISSUE THREAD

**Issue by marshalmiller** [rottingresearch/rottingresearch#77]
<img width="526" alt="Screen Shot 2022-10-25 at 7 55 14 PM" src="https://user-images.githubusercontent.com/30907840/197903446-70e0a5e5-5a0b-4ebb-b3c6-0506367cf646.png">

We should remove the ability to paste a link and limit it to just uploading a file. The reason is because of copyright issues. Publishers tend to be highly litigious. With the link feature, the website downloads a copy and analyzes it, whereas when someone uploads a file, they are bound to the user agreement and release the site of any responsibility. I know this is pretty cynical, but I think it's an unfortunate reality. If someone wants to run it on remote files, they can use the Python app, Linkrot.

**Comment by william-monroy** [comment]
Hi @marshalmiller, could you assign me this issue?

**Comment by william-monroy** [comment]
@marshalmiller Do you want the website look like this:
<img width="511" alt="Captura de Pantalla 2022-10-25 a la(s) 20 33 10" src="https://user-images.githubusercontent.com/58092741/197916993-afc642ad-b0a9-45ee-9ff4-65f7be14305a.png">

**Comment by marshalmiller** [comment]
@william-monroy i think this looks good. We can always clean it up and we continue to move forward, if necessary.

**Comment by marshalmiller** [comment]
@william-monroy I wanted to send you a reminder that if you wanted to submit this for credit for Hacktoberfest, PRs must be submitted by tomorrow. Thank you for your contribution.

**Comment by aditirao7** [comment]
Hi @marshalmiller this issue can be closed right? Unless there's something else?

**Comment by marshalmiller** [comment]
@aditirao7 Correct. Resolved in #143
